const legendary = [
    {"name": "articuno"},
    {"name": "zapdos"},
    {"name": "moltres"},
    {"name": "mewtwo"},
    {"name": "raikou"},
    {"name": "entei"},
    {"name": "suicune"},
    {"name": "lugia"},
    {"name": "ho-oh"},
    {"name": "regice"},
    {"name": "registeel"},
    {"name": "regirock"},
    {"name": "latias"},
    {"name": "latios"},
    {"name": "groudon"},
    {"name": "kyogre"},
    {"name": "rayquaza"},
    {"name": "uxie"},
    {"name": "mesprit"},
    {"name": "azelf"},
    {"name": "dialga"},
    {"name": "palkia"},
    {"name": "giratina"},
    {"name": "cresselia"},
    {"name": "heatran"},
    {"name": "regigigas"},

    {"name": "cobalion"},
    {"name": "terrakion"},
    {"name": "virizion"},
    {"name": "tornadus"},
    {"name": "thundurus"},
    {"name": "landorus"},
    {"name": "zekrom"},
    {"name": "reshiram"},
    {"name": "kyurem"},
     
    {"name": "xerneas"},
    {"name": "yveltal"},
    {"name": "zygarde"},
     
    {"name": "type-null"},
    {"name": "silvally"},
    {"name": "tapu-koko"},
    {"name": "tapu-lele"},
    {"name": "tapu-bulu"},
    {"name": "tapu-fini"},
    {"name": "cosmog"},
    {"name": "cosmoem"},
    {"name": "solgaleo"},
    {"name": "lunala"},
    {"name": "necrozma"},

    {"name": "zacian"},
    {"name": "zamazenta"},
    {"name": "eternatus"},
    {"name": "kubfu"},
    {"name": "urshifu"},
    {"name": "regieleki"},
    {"name": "regidrago"},
    {"name": "glastrier"},
    {"name": "spectrier"},
    {"name": "calyrex"},
    {"name": "enamorus"},

    {"name": "wo-chien"},
    {"name": "chien-pao"},
    {"name": "ting-lu"},
    {"name": "chi-yu"},
    {"name": "koraidon"},
    {"name": "miraidon"},
    {"name": "okidogi"},
    {"name": "munkidori"},
    {"name": "fezandipiti"},
    {"name": "ogerpon"},
    // {"name": "terapagos"}, 
     
]

export default legendary;